### ISSUE TITLE
New Universal Ctags version available

### ISSUE THREAD

**Issue by pidgeon777** [pnedev/nppgtags#21]
Hi, I noticed that your Universal Ctags latest included version is the following:

```
Universal Ctags 0.0.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jan  1 2016, 11:12:30
  URL: https://ctags.io/
```
It seems that a new Universal Ctags has been very recently released here:

https://github.com/universal-ctags/ctags-win32/releases

Just in case you would think about integrating it on your next release. Maybe it adds compatibility with many other programming languages.

**Comment by pnedev** [comment]
Updating to the latest Universal Ctags is a good idea I agree.
When I have more time.

**Comment by AntonDevil** [comment]
Actually, there is another issue related to binary update.

"VB" langmap from gtags.conf changed its name to "VB.net".
Can't parse VBs now because my pygments v2.11.2 (Python 3) don't know what "VB" alias is (it expects new "VB.net" already).

Binary update should fix that and I glad to see some activity around it.
I guess the only blocker is that NppGTags.dll need to be recompiled.
BTW, is there a way to make NppGTags.dll such that it don't need recompilation next time binaries update?

Can't wait to get updated version of the plugin =).

Thanks!

**Comment by pnedev** [comment]
@AntonDevil  ,

Could you please test if you still have that problem with the new release 5.0.0?
You can find it here: https://github.com/pnedev/nppgtags/releases/tag/v5.0.0
From the Assets section get the archive corresponding to your Notepad++ release - x86 or x64.
You'll need Notepad++ v8.4.1 or higher.

**Comment by pnedev** [comment]
@AntonDevil ,

> BTW, wanted to ask you what you do when switch branches in git?

The code-bases I work on are not so big so after each branch-switch I re-create the database.
It is not optimal for your case but unless you decide to upload the database to git so it automatically switches with the branch (which is really bad) the other option I would suggest is to make a kind of storage folder structure representing the git branches and store there the pre-generated branch databases. Then make a script that switches branches that stores the current branch database in the proper place in the folder structure and then switches the git branch and then gets the corresponding database for the new branch from the folder structure and copies it in the project folder.

> Search in Other Files

That message is normal and is displayed when the plugin detects that the database is probably not updated. That happens if you change the files from outside Notepad++ (including switching git branches for instance) or you change the files from Notepad++ but you haven't saved them so the database is not updated. This means you need to re-create database.

> Create Database

That warning is ctags.exe related and the plugin simply displays it for you. It doesn't seem critical so you can just close the message and disregard it. The problem is that it might appear every time the database is updated which might become annoying.
If that's the case please open another ticket here describing that behavior so I can think of a way to circumvent that in future releases.

BR

**Comment by AntonDevil** [comment]
> The problem is that it might appear every time the database is updated which might become annoying.
If that's the case please open another ticket here describing that behavior so I can think of a way to circumvent that in future releases.

I think it is good as it is.

Thanks again!
