### ISSUE TITLE
Gtags 6.5.6

### ISSUE THREAD

**Issue by chcg** [pnedev/nppgtags#3]
See http://adoxa.altervista.org/global/ version 6.5.6 is available in the meantime, also a little bit unclear what changed as no release notes are linked at
https://www.gnu.org/software/global/whatsnew.html
, but see:
6.5.6:
https://lists.gnu.org/archive/html/info-global/2016-12/msg00000.html
6.5.5
https://lists.gnu.org/archive/html/info-global/2016-09/msg00000.html
6.5.4 and 6.5.3
https://lists.gnu.org/archive/html/info-global/2016-03/index.html

**Comment by pnedev** [comment]
Hello @chcg ,

Yes, I saw the new version 6.5.6 but I hesitate if I should update.
Jason never released Win32 version of 6.5.4 nor 6.5.5 and I never observed Universal Ctags parser problems in Win32 6.5.3 version. Perhaps he had fixed whatever issue was there while porting the official 6.5.3 to Win32, I don't know.
The issue with database deletion on re-parse is bad indeed. I need to verify it is actually fixed in 6.5.6 Win version (it is a fix from 6.5.5 actually but again no Win32 version 6.5.5 is available).
Version 6.5.6 is not important for NppGTags use case as the plugin doesn't use htags. Gtags hooks are also not needed. The length bug fix is the only useful thing here but in the plugin I limit the tag size search to 128 anyway so nothing important here.

When I downloaded Win32 6.5.6 release some time ago I did a check at https://www.virustotal.com and I got some positives. That's the main reason for my hesitation actually. I know that often there are false positives but as nothing important appeared to be changed since v 6.5.3 I decided not to upgrade.
I'll reconsider this because of the issue fixed in 6.5.5, thank you.

BR

**Comment by pnedev** [comment]
OK, the threat detection ration at https://www.virustotal.com/ is fairly low and the most trusted scanners don't find anything suspicious so I updated to v6.5.6: https://github.com/pnedev/nppgtags/commit/441543f7b013ae07684c577b0b7d81255f67a7bf.
