### ISSUE TITLE
double click on search result line cant go to the source location

### ISSUE THREAD

**Issue by EdmundLaiCH** [pnedev/nppgtags#34]
with new update 64bit npp, 8.4 , it still can search but when double click on the search result cant go to the loctaion

**Comment by PeanutWakuWaku** [comment]
I am having same problem as @EdmundLaiCH .
The problem happened after I update Notepad++ to version 8.4.2(64bit). I am using Windows 10 Pro.

"Cant go to location" means after I clicked the result in the NppGTags window, the file is not opened ( meaning nothing happens when clicking the result ).

Also after the problem happened, I tried to reinstall older version of Notepad++ and reinstall this plugin. But the problem still persists.
Tried Notepad++ version: 8.4 , 8.4.1 , 8.4.2 .

**Comment by pnedev** [comment]
@PeanutWakuWaku ,

Yes, NppGTags versions below 5.0.0 are incompatible with Notepad++ versions above 8.3.3 because of internal Scintilla component changes.

And because in the plugin lists of N++ 8.4, 8.4.1 and 8.4.2 NppGTags plugin is not updated yet (it took some time to fix the incompatibilities) there is no officially released compatible plugin version (that is through N++ Plugins Admin).

I assume your NppGTags version is not 5.0.0 so you can either wait for Notepad++ 8.4.3 to be released (it will have access to the new NppGTags 5.0.0) or you can manually download the new 5.0.0 version from https://github.com/pnedev/nppgtags/releases/tag/v5.0.0 - get the zip that matches your Notepad++ bit-ness extract it and replace your plugin files in Notepad++'s plugins folder.

**Comment by PeanutWakuWaku** [comment]
@pnedev 

The problem is solved after I install NppGTags version 5.0.0.

Thank you. 👍👍
