### ISSUE TITLE
Find definition and find references always result in find symbol even after creating database for project

### ISSUE THREAD

**Issue by dhowland** [pnedev/nppgtags#6]
Title says it all really.  I've set up a C project with several files, and I can't ever get find definition to work.  Now, once it falls back on "find symobl" it does find the file and location that define the variable.  Also autocomplete does show me symbols from the entire project, so I can't explain why it isn't working.  Does find definition only work for functions and not globals?

**Comment by dhowland** [comment]
Nevermind, this is a limitation of GLOBAL.

Per the plans at https://www.gnu.org/software/global/plans.html
"Treat variable definitions as a definition tag (GTAGS). "

**Comment by pnedev** [comment]
Hello @dhowland ,

> Nevermind, this is a limitation of GLOBAL.

Yes, correct.
The Autocomplete is showing symbols as well, that's why you see the variable in the list.

The limitation is actually in the GLOBAL default parser (gtags.exe).
You can go to your project's NppGTags settings (just open a file from your project and open the plugin Settings) and select in the Code Parser drop-down _ctags_ as parser. It will index globals definitions but ctags doesn't support reference lookup. You can also use _pygments_ parser - it is the slowest in indexing but supports globals definitions and reference lookup (it actually extends ctags functionality with reference indexing).

Local variables definitions are not extracted by any of the parsers.

BR

**Comment by dhowland** [comment]
Thanks.  I did install pygments because I wanted to use gtags with Python.

Locals are fine.  I don't expect (or want) locals to be indexed.

Thanks, and great plugin!
