### ISSUE TITLE
Add command Go To File/Definition/Reference

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [pnedev/nppgtags#9]
Any chance add that commands? They would automatically move to the indicated place, without opening bottom find panel where we must manually select correct hint.
If we need only fast go/back between different places in our code it would be a good improvement.

**Comment by ArkadiuszMichalski** [comment]
For code example:
```
function test(){
}
.
.
.
.

test();
```
When I have coursor near `test();` I just want go to the `function test()` definition without opening bottom find panel where I must manually select and click on that definition. In most case this panel requires additional work from us, which is unnecessary.

**Comment by ArkadiuszMichalski** [comment]
Looks like someone ask the same some time ago:
https://sourceforge.net/p/nppgtags/discussion/general/thread/15423aa7/
Clicking on definition with ctrl is also good idea, but having a separate command allows you to assign any shortcut and use this command by other plugins (like NppExec, Python Script).

**Comment by pnedev** [comment]
Thanks for the explanation.

Well, the request from the Sourceforge link is a bit different. It was for a pop-up window exactly near the tag look-up (quite like the auto-completion).

As far as I understand you, You would like to go directly to the definition instead of opening any window first. The problem with it is that there might be more definitions instead of only one. The GTags parsers do not take into account the scope (namespace, class, code scope in general). So if you have a C++ class and you search for its definition you will get both the class itself and the constructor. If you have the function `void example()` and `int example(char)` you will get both in the definitions list.
If we are also talking about references those are almost always more than one (not to mention that sometimes you just what to see where the function is called and not details about the call).

Adding separate command for the limited case when you have only one definition is overkill - it unnecessary 'pollutes' the plugin menu.
It is possible though to go to the definition directly IF there is only one match. Same is true for the reference search. Personally I don't like it but if you find it useful I can add an option to enable it.
What do you think?

**Comment by ArkadiuszMichalski** [comment]
Relative referred Sourceforge it depends on repeated definitions in different files, if we have only one we don't get any pop-up, just jump to that definition.
Backing to nppgtags, looks like in my case additional option will be enough, separate commands are not necessary.

**Comment by ArkadiuszMichalski** [comment]
One more thing, please do the same with File command, when we have only one file then jump to them.
I use a lot of import with unique path, so in my perspective is faster invoke `Find files` from nppgtags instead of using any other list of file (Tabbar, Project/Folders or Document Switcher), I just do not have to remember where this files exist (nested folders), just select name and go.

**Comment by BlackHole27** [comment]
It's great idea.

**Comment by pnedev** [comment]
After so much time automatic single result opening is finally implemented.
It will be included in the next release (5.0.0)
